name: chat
description: A new Flutter application.

publish_to: 'none'
version: 2.2.0+8

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.2.4
  firebase_storage: ^10.0.6
  firebase_database: ^8.0.1
  paginate_firestore: ^1.0.2
  permission_handler: ^8.1.4+2
  google_sign_in: ^5.2.0
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.13.3
  the_apple_sign_in: ^1.1.1
  onesignal_flutter: ^3.2.4

  nb_utils: ^4.4.7
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  cached_network_image: ^3.1.0
  image_picker: ^0.8.3+2
  flutter_svg: ^0.22.0
  image_crop: ^0.4.0
  url_launcher: ^6.0.3
  share: ^2.0.4
  package_info: ^2.0.2
  html: ^0.15.0
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.1
  file_picker: ^3.0.4
  just_audio: ^0.9.5
  cached_video_player: ^2.0.0-dev.1
#  audioplayers: ^0.19.1
  video_thumbnail: ^0.4.3

  geolocator: ^7.6.1

  agora_rtc_engine: ^4.0.6
  sqflite: ^2.0.0+3

  mobx: ^2.0.4
  flutter_mobx: ^2.0.2

#  story_view: ^0.13.1

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  mobx_codegen: ^2.0.1+3
  #flutter packages pub run build_runner build --delete-conflicting-outputs
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/sticker/
    - assets/Wallpaper/bright_wallpaper/
    - assets/Wallpaper/dark_wallpaper/
    - assets/Wallpaper/solid_wallpaper/
    - assets/flags/
    - lang/


